name: givt_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_sim_country_code: ^0.1.2
  flutter_native_timezone: ^2.0.0
  get_it: ^7.6.0
  http: ^0.13.6
  http_interceptor: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  shared_preferences: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/