name: givt_app
description: A Very Good Project created by Very Good CLI.
version: 3.16.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  amplitude_flutter: ^3.13.0
  badges: ^3.1.1
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_sim_country_code: ^0.1.2
  get_it: ^7.6.0
  http: ^0.13.6
  http_interceptor: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  shared_preferences: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
#   fonts:
#     - family: Avenir
#       fonts:
#         - asset: fonts/AvenirLTStd-Black.ttf
#         - asset: fonts/AvenirLTStd-BlackOblique.ttf
#         - asset: fonts/AvenirLTStd-Book.ttf
#         - asset: fonts/AvenirLTStd-BookOblique.ttf
#         - asset: fonts/AvenirLTStd-Heavy.ttf
#         - asset: fonts/AvenirLTStd-HeavyOblique.ttf
#         - asset: fonts/AvenirLTStd-Light.ttf
#         - asset: fonts/AvenirLTStd-LightOblique.ttf
#         - asset: fonts/AvenirLTStd-Medium.ttf
#         - asset: fonts/AvenirLTStd-MediumOblique.ttf
#         - asset: fonts/AvenirLTStd-Oblique.ttf
#         - asset: fonts/AvenirLTStd-Roman.ttf
  assets:
    - assets/images/        
